export const TOURS = [
  {
    "id": "van-nisa",
    "city": "van",
    "cityLabel": "وان",
    "region": "turkey",
    "kind": "international",
    "title": "وان · NISA",
    "meta": "۲ شب و ۳ روز · زمینی · هتل ۳ ستاره",
    "hotel": "NISA",
    "price": 10230000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "van-dosco",
    "city": "van",
    "cityLabel": "وان",
    "region": "turkey",
    "kind": "international",
    "title": "وان · DOSCO",
    "meta": "۲ شب و ۳ روز · زمینی · هتل ۳ ستاره",
    "hotel": "DOSCO",
    "price": 13500000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "van-haldi",
    "city": "van",
    "cityLabel": "وان",
    "region": "turkey",
    "kind": "international",
    "title": "وان · HALDI",
    "meta": "۲ شب و ۳ روز · زمینی · هتل ۴ ستاره",
    "hotel": "HALDI",
    "price": 19400000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "van-tamara",
    "city": "van",
    "cityLabel": "وان",
    "region": "turkey",
    "kind": "international",
    "title": "وان · TAMARA",
    "meta": "۳ شب و ۴ روز · زمینی · هتل ۴ ستاره",
    "hotel": "TAMARA",
    "price": 19980000,
    "services": "لوکیشن مرکزی · BB · ترنسفر",
    "tag": "پرفروش",
    "continent": "asia"
  },
  {
    "id": "mashhad-miami",
    "city": "mashhad",
    "cityLabel": "مشهد",
    "region": "domestic",
    "kind": "domestic",
    "title": "مشهد · هتل میامی",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۳ ستاره",
    "hotel": "میامی",
    "price": 16200000,
    "services": "پرواز رفت‌وبرگشت · صبحانه",
    "tag": "داخلی",
    "continent": "iran"
  },
  {
    "id": "mashhad-shiraz",
    "city": "mashhad",
    "cityLabel": "مشهد",
    "region": "domestic",
    "kind": "domestic",
    "title": "مشهد · هتل شیراز",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۳ ستاره",
    "hotel": "شیراز",
    "price": 16500000,
    "services": "پرواز رفت‌وبرگشت · صبحانه",
    "tag": "داخلی",
    "continent": "iran"
  },
  {
    "id": "mashhad-fazilat",
    "city": "mashhad",
    "cityLabel": "مشهد",
    "region": "domestic",
    "kind": "domestic",
    "title": "مشهد · هتل فضیلت",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۴ ستاره",
    "hotel": "فضیلت",
    "price": 17200000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "منتخب",
    "continent": "iran"
  },
  {
    "id": "mashhad-almas2",
    "city": "mashhad",
    "cityLabel": "مشهد",
    "region": "domestic",
    "kind": "domestic",
    "title": "مشهد · الماس ۲",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۵ ستاره",
    "hotel": "الماس ۲",
    "price": 19400000,
    "services": "پرواز رفت‌وبرگشت · صبحانه",
    "tag": "لوکس",
    "continent": "iran"
  },
  {
    "id": "kish-helia",
    "city": "kish",
    "cityLabel": "کیش",
    "region": "domestic",
    "kind": "domestic",
    "title": "کیش · هتل هلیا",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۳ ستاره",
    "hotel": "هلیا",
    "price": 19570000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "داخلی",
    "continent": "iran"
  },
  {
    "id": "kish-sadaf",
    "city": "kish",
    "cityLabel": "کیش",
    "region": "domestic",
    "kind": "domestic",
    "title": "کیش · هتل صدف",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۴ ستاره",
    "hotel": "صدف",
    "price": 20615000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "منتخب",
    "continent": "iran"
  },
  {
    "id": "kish-aramis",
    "city": "kish",
    "cityLabel": "کیش",
    "region": "domestic",
    "kind": "domestic",
    "title": "کیش · هتل آرامیس",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۴ ستاره",
    "hotel": "آرامیس",
    "price": 21850000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "منتخب",
    "continent": "iran"
  },
  {
    "id": "armenia-baxos-ground",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · BAXOS زمینی",
    "meta": "۳ شب و ۴ روز · اتوبوس · هتل ۳ ستاره",
    "hotel": "BAXOS",
    "price": 27500000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "armenia-shirak-ground",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · SHIRAK زمینی",
    "meta": "۳ شب و ۴ روز · اتوبوس · هتل ۳ ستاره",
    "hotel": "SHIRAK",
    "price": 28900000,
    "services": "لوکیشن مرکزی · BB · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "armenia-baxos-air",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · BAXOS هوایی",
    "meta": "۲ شب و ۳ روز · پرواز · هتل ۳ ستاره",
    "hotel": "BAXOS",
    "price": 38730000,
    "services": "بیمه · سیمکارت · صبحانه",
    "tag": "هوایی",
    "continent": "asia"
  },
  {
    "id": "armenia-primer",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · PRIMER",
    "meta": "۳ شب و ۴ روز · پرواز · هتل ۳ ستاره",
    "hotel": "PRIMER",
    "price": 39900000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "پرفروش",
    "continent": "asia"
  },
  {
    "id": "armenia-anigrand",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · ANI GRAND",
    "meta": "۳ شب و ۴ روز · پرواز · هتل ۵ ستاره",
    "hotel": "ANI GRAND",
    "price": 61380000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "armenia-radisson",
    "city": "armenia",
    "cityLabel": "ارمنستان",
    "region": "asia",
    "kind": "international",
    "title": "ایروان · RADISSON BLU",
    "meta": "۳ شب و ۴ روز · پرواز · هتل ۵ ستاره",
    "hotel": "RADISSON BLU",
    "price": 71700000,
    "services": "بیمه · سیمکارت · صبحانه",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "istanbul-rota-ground",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ROTA STAR زمینی",
    "meta": "۳ شب و ۴ روز · زمینی · هتل ۳ ستاره",
    "hotel": "ROTA STAR",
    "price": 28990000,
    "services": "تکسیم · BB · لیدر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "istanbul-rota-air",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ROTA STAR",
    "meta": "۲ شب و ۳ روز · ایران ایر · هتل ۳ ستاره",
    "hotel": "ROTA STAR",
    "price": 43200000,
    "services": "بی‌اوغلو · BB · ترنسفر",
    "tag": "کوتاه",
    "continent": "asia"
  },
  {
    "id": "istanbul-white",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · WHITE MONARCH",
    "meta": "۳ شب و ۴ روز · معراج · هتل ۴ ستاره",
    "hotel": "WHITE MONARCH",
    "price": 48700000,
    "services": "شیشلی · BB · ترنسفر",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "istanbul-cartoon",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · CARTOON",
    "meta": "۳ شب و ۴ روز · معراج · هتل ۴ ستاره",
    "hotel": "CARTOON",
    "price": 55000000,
    "services": "تکسیم · BB · ترنسفر",
    "tag": "پرفروش",
    "continent": "asia"
  },
  {
    "id": "istanbul-cher",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · CHER",
    "meta": "۳ شب و ۴ روز · معراج · هتل ۵ ستاره",
    "hotel": "CHER",
    "price": 60000000,
    "services": "بی‌اوغلو · BB · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "istanbul-elite4",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ELITE WORLD",
    "meta": "۳ شب و ۴ روز · معراج · هتل ۵ ستاره",
    "hotel": "ELITE WORLD",
    "price": 69950000,
    "services": "تکسیم · BB · ترنسفر",
    "tag": "Signature",
    "continent": "asia"
  },
  {
    "id": "istanbul-elite5",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ELITE WORLD",
    "meta": "۴ شب و ۵ روز · معراج · هتل ۵ ستاره",
    "hotel": "ELITE WORLD",
    "price": 83000000,
    "services": "تکسیم · BB · ترنسفر",
    "tag": "Signature",
    "continent": "asia"
  },
  {
    "id": "istanbul-elite6",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ELITE WORLD",
    "meta": "۵ شب و ۶ روز · معراج · هتل ۵ ستاره",
    "hotel": "ELITE WORLD",
    "price": 94200000,
    "services": "تکسیم · BB · ترنسفر",
    "tag": "Signature",
    "continent": "asia"
  },
  {
    "id": "istanbul-elite8",
    "city": "istanbul",
    "cityLabel": "استانبول",
    "region": "turkey",
    "kind": "international",
    "title": "استانبول · ELITE WORLD",
    "meta": "۷ شب و ۸ روز · معراج · هتل ۵ ستاره",
    "hotel": "ELITE WORLD",
    "price": 108900000,
    "services": "تکسیم · BB · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "georgia-rustaveli",
    "city": "georgia",
    "cityLabel": "گرجستان",
    "region": "asia",
    "kind": "international",
    "title": "تفلیس · RUSTAVELI 36",
    "meta": "۴ شب و ۵ روز · سپهران · هتل ۳ ستاره",
    "hotel": "RUSTAVELI 36",
    "price": 36500000,
    "services": "مرکز شهر · BB · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "georgia-isaka",
    "city": "georgia",
    "cityLabel": "گرجستان",
    "region": "asia",
    "kind": "international",
    "title": "تفلیس · ISAKA",
    "meta": "۴ شب و ۵ روز · سپهران · هتل ۳ ستاره",
    "hotel": "ISAKA",
    "price": 39750000,
    "services": "مرکز شهر · BB · ترنسفر",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "georgia-lm",
    "city": "georgia",
    "cityLabel": "گرجستان",
    "region": "asia",
    "kind": "international",
    "title": "تفلیس · LM CLUB",
    "meta": "۳ شب و ۴ روز · سپهران · هتل ۴ ستاره",
    "hotel": "LM CLUB",
    "price": 41230000,
    "services": "مرکز شهر · BB · ترنسفر",
    "tag": "پرفروش",
    "continent": "asia"
  },
  {
    "id": "georgia-batumi",
    "city": "georgia",
    "cityLabel": "گرجستان",
    "region": "asia",
    "kind": "international",
    "title": "باتومی · ROYAL GEORGIA",
    "meta": "۳ شب و ۴ روز · وارش · هتل ۴ ستاره",
    "hotel": "ROYAL GEORGIA",
    "price": 47700000,
    "services": "پرواز · بیمه · صبحانه",
    "tag": "ساحلی",
    "continent": "asia"
  },
  {
    "id": "georgia-combo",
    "city": "georgia",
    "cityLabel": "گرجستان",
    "region": "asia",
    "kind": "international",
    "title": "تفلیس + باتومی · ISAKA",
    "meta": "۵ شب و ۶ روز · ترکیبی · هتل ۳ ستاره",
    "hotel": "ISAKA",
    "price": 61700000,
    "services": "پرواز · بیمه · صبحانه",
    "tag": "ترکیبی",
    "continent": "asia"
  },
  {
    "id": "oman-safeer",
    "city": "oman",
    "cityLabel": "عمان",
    "region": "gulf",
    "kind": "international",
    "title": "مسقط · SAFEER INTERNATIONAL",
    "meta": "۲ شب و ۳ روز · سپهران · هتل ۳ ستاره",
    "hotel": "SAFEER INTERNATIONAL",
    "price": 39690000,
    "services": "BB · لیدر · بیمه",
    "tag": "کوتاه",
    "continent": "asia"
  },
  {
    "id": "oman-larosa",
    "city": "oman",
    "cityLabel": "عمان",
    "region": "gulf",
    "kind": "international",
    "title": "مسقط · LA ROSA",
    "meta": "۲ شب و ۳ روز · سپهران · هتل ۳ ستاره",
    "hotel": "LA ROSA",
    "price": 39790000,
    "services": "BB · لیدر · بیمه",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "oman-carnelian",
    "city": "oman",
    "cityLabel": "عمان",
    "region": "gulf",
    "kind": "international",
    "title": "مسقط · CARNELIAN BY GLORY",
    "meta": "۳ شب و ۴ روز · سپهران · هتل ۴ ستاره",
    "hotel": "CARNELIAN BY GLORY",
    "price": 46990000,
    "services": "پرواز · صبحانه · بیمه",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "oman-sheraton",
    "city": "oman",
    "cityLabel": "عمان",
    "region": "gulf",
    "kind": "international",
    "title": "مسقط · SHERATON",
    "meta": "۲ شب و ۳ روز · ماهان · هتل ۵ ستاره",
    "hotel": "SHERATON",
    "price": 54990000,
    "services": "BB · لیدر · آفر ویژه",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "baku-royal",
    "city": "baku",
    "cityLabel": "باکو",
    "region": "asia",
    "kind": "international",
    "title": "باکو · ROYAL",
    "meta": "۳ شب و ۴ روز · ایران ایر · هتل ۳ ستاره",
    "hotel": "ROYAL",
    "price": 69100000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "اقتصادی",
    "continent": "asia"
  },
  {
    "id": "baku-iris",
    "city": "baku",
    "cityLabel": "باکو",
    "region": "asia",
    "kind": "international",
    "title": "باکو · IRIS",
    "meta": "۳ شب و ۴ روز · ایران ایر · هتل ۴ ستاره",
    "hotel": "IRIS",
    "price": 79500000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "baku-sapphire",
    "city": "baku",
    "cityLabel": "باکو",
    "region": "asia",
    "kind": "international",
    "title": "باکو · SAPPHIRE MARINE",
    "meta": "۴ شب و ۵ روز · ایران ایر · هتل ۵ ستاره",
    "hotel": "SAPPHIRE MARINE",
    "price": 100500000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "izmir-alican",
    "city": "izmir",
    "cityLabel": "ازمیر",
    "region": "turkey",
    "kind": "international",
    "title": "ازمیر · ALICAN",
    "meta": "۶ شب و ۷ روز · کاسپین · هتل ۳ ستاره",
    "hotel": "ALICAN",
    "price": 82200000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "ترکیه",
    "continent": "asia"
  },
  {
    "id": "kusadasi-izmir",
    "city": "kusadasi",
    "cityLabel": "کوش‌آداسی",
    "region": "turkey",
    "kind": "international",
    "title": "کوش‌آداسی + ازمیر",
    "meta": "۶ شب و ۷ روز · کاسپین · هتل ۳ ستاره",
    "hotel": "MELKE / LIFE CORNER",
    "price": 76100000,
    "services": "پرواز · UALL · ترنسفر",
    "tag": "ترکیبی",
    "continent": "asia"
  },
  {
    "id": "bodrum-beach",
    "city": "bodrum",
    "cityLabel": "بدروم",
    "region": "turkey",
    "kind": "international",
    "title": "بدروم · BODRUM BEACH",
    "meta": "۶ شب و ۷ روز · کاسپین · هتل ۴ ستاره",
    "hotel": "BODRUM BEACH",
    "price": 99200000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "ساحلی",
    "continent": "asia"
  },
  {
    "id": "marmaris-serin",
    "city": "marmaris",
    "cityLabel": "مارماریس",
    "region": "turkey",
    "kind": "international",
    "title": "مارماریس · SERIN",
    "meta": "۶ شب و ۷ روز · معراج · هتل ۳ ستاره",
    "hotel": "SERIN",
    "price": 107000000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "ساحلی",
    "continent": "asia"
  },
  {
    "id": "fethiye-garcia",
    "city": "fethiye",
    "cityLabel": "فتحیه",
    "region": "turkey",
    "kind": "international",
    "title": "فتحیه · GARCIA RESORT & SPA",
    "meta": "۶ شب و ۷ روز · معراج · هتل ۵ ستاره",
    "hotel": "GARCIA RESORT & SPA",
    "price": 182500000,
    "services": "UALL · لیدر · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "thailand-pattaya-train",
    "city": "thailand",
    "cityLabel": "تایلند",
    "region": "asia",
    "kind": "international",
    "title": "پاتایا · THE TRAIN RESORT",
    "meta": "۷ شب و ۸ روز · ماهان · هتل ۳ ستاره",
    "hotel": "THE TRAIN RESORT",
    "price": 112500000,
    "services": "BB · لیدر · ویزا",
    "tag": "تایلند",
    "continent": "asia"
  },
  {
    "id": "thailand-phuket",
    "city": "thailand",
    "cityLabel": "تایلند",
    "region": "asia",
    "kind": "international",
    "title": "پوکت · PATONG BAY HILL",
    "meta": "۷ شب و ۸ روز · هتل ۳ ستاره",
    "hotel": "PATONG BAY HILL",
    "price": 115900000,
    "services": "پرواز · صبحانه · ویزا",
    "tag": "پوکت",
    "continent": "asia"
  },
  {
    "id": "thailand-pattaya-mandarin",
    "city": "thailand",
    "cityLabel": "تایلند",
    "region": "asia",
    "kind": "international",
    "title": "پاتایا · MANDITEL NORTH",
    "meta": "۷ شب و ۸ روز · ماهان · هتل ۳ ستاره",
    "hotel": "MANDITEL NORTH",
    "price": 119900000,
    "services": "BB · لیدر · ویزا",
    "tag": "پاتایا",
    "continent": "asia"
  },
  {
    "id": "thailand-combo",
    "city": "thailand",
    "cityLabel": "تایلند",
    "region": "asia",
    "kind": "international",
    "title": "پاتایا + بانکوک",
    "meta": "۷ شب و ۸ روز · ماهان · هتل ۳ ستاره",
    "hotel": "GRAND DAY",
    "price": 128000000,
    "services": "BB · لیدر · ویزا",
    "tag": "ترکیبی",
    "continent": "asia"
  },
  {
    "id": "bali",
    "city": "bali",
    "cityLabel": "بالی",
    "region": "asia",
    "kind": "international",
    "title": "بالی · ۷ شب",
    "meta": "۷ شب و ۸ روز · ایران ایرتور · هتل ۴ ستاره",
    "hotel": "4★ HOTEL",
    "price": 149350000,
    "services": "پرواز · صبحانه · لیدر",
    "tag": "خاص",
    "continent": "asia"
  },
  {
    "id": "malaysia-asto",
    "city": "malaysia",
    "cityLabel": "مالزی",
    "region": "asia",
    "kind": "international",
    "title": "کوالالامپور · ASTO",
    "meta": "۷ شب و ۸ روز · ایران ایرتور · هتل ۳ ستاره",
    "hotel": "ASTO",
    "price": 157300000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "مالزی",
    "continent": "asia"
  },
  {
    "id": "malaysia-regalia",
    "city": "malaysia",
    "cityLabel": "مالزی",
    "region": "asia",
    "kind": "international",
    "title": "کوالالامپور · REGALIA UPPER VIEW",
    "meta": "۷ شب و ۸ روز · ایران ایرتور · هتل ۴ ستاره",
    "hotel": "REGALIA UPPER VIEW",
    "price": 165700000,
    "services": "BB · لیدر · آفر ویژه",
    "tag": "منتخب",
    "continent": "asia"
  },
  {
    "id": "malaysia-royal",
    "city": "malaysia",
    "cityLabel": "مالزی",
    "region": "asia",
    "kind": "international",
    "title": "کوالالامپور · ROYAL CHULAN",
    "meta": "۷ شب و ۸ روز · ایران ایرتور · هتل ۵ ستاره",
    "hotel": "ROYAL CHULAN",
    "price": 188300000,
    "services": "BB · لیدر · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "russia-4",
    "city": "russia",
    "cityLabel": "روسیه",
    "region": "europe",
    "kind": "international",
    "title": "مسکو + سنت‌پترزبورگ",
    "meta": "۷ شب و ۸ روز · معراج · هتل ۴ ستاره",
    "hotel": "VEGA + ART NUVO PALACE",
    "price": 158000000,
    "services": "BB · گشت با ناهار · ویزا",
    "tag": "ترکیبی",
    "continent": "europe"
  },
  {
    "id": "russia-5",
    "city": "russia",
    "cityLabel": "روسیه",
    "region": "europe",
    "kind": "international",
    "title": "مسکو + سنت‌پترزبورگ · 5★",
    "meta": "۷ شب و ۸ روز · معراج · هتل ۵ ستاره",
    "hotel": "RADISSON BLU + RENARTISS",
    "price": 265000000,
    "services": "BB · گشت با ناهار · ویزا",
    "tag": "لوکس",
    "continent": "europe"
  },
  {
    "id": "tunisia",
    "city": "tunisia",
    "cityLabel": "تونس",
    "region": "africa",
    "kind": "international",
    "title": "تونس + سوسه + حمامت",
    "meta": "۷ شب و ۸ روز · معراج · هتل ۵ ستاره",
    "hotel": "TROPICANA CLUB",
    "price": 220900000,
    "services": "AL · لیدر · ترنسفر",
    "tag": "ترکیبی",
    "continent": "africa"
  },
  {
    "id": "vietnam-4",
    "city": "vietnam",
    "cityLabel": "ویتنام",
    "region": "asia",
    "kind": "international",
    "title": "دانانگ + هانوی + کروز",
    "meta": "۹ شب و ۱۰ روز · معراج · هتل ۴ ستاره",
    "hotel": "EDEN OCEAN",
    "price": 379000000,
    "services": "BB · گشت خرید · ترنسفر",
    "tag": "خاص",
    "continent": "asia"
  },
  {
    "id": "vietnam-5",
    "city": "vietnam",
    "cityLabel": "ویتنام",
    "region": "asia",
    "kind": "international",
    "title": "ویتنام Signature",
    "meta": "۹ شب و ۱۰ روز · معراج · هتل ۵ ستاره",
    "hotel": "WINK ICON",
    "price": 416000000,
    "services": "BB · گشت خرید · ترنسفر",
    "tag": "لوکس",
    "continent": "asia"
  },
  {
    "id": "antalya-nirvana",
    "city": "antalya",
    "cityLabel": "آنتالیا",
    "region": "turkey",
    "kind": "international",
    "title": "آنتالیا · NIRVANA COSMOPOLITAN",
    "meta": "۶ شب و ۷ روز · معراج · هتل ۵ ستاره",
    "hotel": "NIRVANA COSMOPOLITAN",
    "price": 322500000,
    "services": "لارا · UAL · ترنسفر",
    "tag": "Luxury Resort",
    "continent": "asia"
  },
  {
    "id": "antalya-delphin",
    "city": "antalya",
    "cityLabel": "آنتالیا",
    "region": "turkey",
    "kind": "international",
    "title": "آنتالیا · DELPHIN IMPERIAL",
    "meta": "۶ شب و ۷ روز · معراج · هتل ۵ ستاره",
    "hotel": "DELPHIN IMPERIAL",
    "price": 362000000,
    "services": "لارا · UAL · ترنسفر",
    "tag": "Luxury Resort",
    "continent": "asia"
  },
  {
    "id": "qeshm-enquiry",
    "city": "qeshm",
    "cityLabel": "قشم",
    "region": "domestic",
    "kind": "domestic",
    "title": "تور قشم",
    "meta": "پکیج و تاریخ حرکت بر اساس ظرفیت",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "iran"
  },
  {
    "id": "chabahar-enquiry",
    "city": "chabahar",
    "cityLabel": "چابهار",
    "region": "domestic",
    "kind": "domestic",
    "title": "تور چابهار",
    "meta": "پکیج و تاریخ حرکت بر اساس ظرفیت",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "iran"
  },
  {
    "id": "dubai-enquiry",
    "city": "dubai",
    "cityLabel": "دبی",
    "region": "gulf",
    "kind": "international",
    "title": "تور دبی",
    "meta": "پرواز + هتل + خدمات سفر",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "asia"
  },
  {
    "id": "qatar-enquiry",
    "city": "qatar",
    "cityLabel": "قطر",
    "region": "gulf",
    "kind": "international",
    "title": "تور قطر",
    "meta": "پرواز + هتل + خدمات سفر",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "asia"
  },
  {
    "id": "maldives-enquiry",
    "city": "maldives",
    "cityLabel": "مالدیو",
    "region": "asia",
    "kind": "international",
    "title": "تور مالدیو",
    "meta": "اقامت ریزورت + پرواز",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "asia"
  },
  {
    "id": "srilanka-enquiry",
    "city": "srilanka",
    "cityLabel": "سریلانکا",
    "region": "asia",
    "kind": "international",
    "title": "تور سریلانکا",
    "meta": "پکیج ترکیبی بر اساس تاریخ",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "asia"
  },
  {
    "id": "india-enquiry",
    "city": "india",
    "cityLabel": "هند",
    "region": "asia",
    "kind": "international",
    "title": "تور هند",
    "meta": "پکیج شهرهای منتخب هند",
    "hotel": "",
    "price": null,
    "services": "استعلام ظرفیت و قیمت",
    "tag": "استعلام",
    "continent": "asia"
  },
  {
    "id": "europe-enquiry",
    "city": "europe",
    "cityLabel": "اروپا",
    "region": "europe",
    "kind": "international",
    "title": "تور اروپا",
    "meta": "پکیج‌های اروپایی بر اساس تاریخ و ویزا",
    "hotel": "",
    "price": null,
    "services": "استعلام برنامه و قیمت",
    "tag": "استعلام",
    "continent": "europe"
  },
  {
    "id": "brazil-enquiry",
    "city": "brazil",
    "cityLabel": "برزیل",
    "region": "america",
    "kind": "international",
    "title": "تور برزیل",
    "meta": "پکیج خاص و تاریخ‌محور",
    "hotel": "",
    "price": null,
    "services": "استعلام برنامه و قیمت",
    "tag": "استعلام",
    "continent": "south-america"
  }
] as const;
